### ISSUE TITLE
Emphasize key steps for building/running Perk Tutor in wiki

### ISSUE THREAD

**Issue by 13nas2** [PerkTutor/PerkTutor#11]
Possibly add some information in bold about why certain steps are important
or create a  "Common mistakes" section and list the problems I ran into? 

IE:
Make sure to:
- start Visual Studio from the command prompt using: Slicer.exe –VisualStudio 
- add "PerkTutor-Debug/inner-build/lib/Slicer-4.4/qt-scripted-modules" to module paths

**Comment by mholden8** [comment]
@13nas2 please check the revised version and suggest some further refinements. https://github.com/PerkTutor/PerkTutor/wiki/PerkTutor-Build-Information

**Comment by mholden8** [comment]
Build instructions are up-to-date. Closing issue as there have been no further changes suggested.
